### ISSUE TITLE
[Suggestion] Lever lock when landed

### ISSUE THREAD

**Issue by DeCat4** [gamendegamer321/Lethal-Admin#25] opened 2024-07-28 23:05 UTC
option to lock the lever when the ship has landed, with a config to value you can change to choose the time of day at which it unlocks.

**Comment by gamendegamer321** [comment] 2024-07-29 10:49
I don't think this is possible with the mod only running for the host.

If I were to block the game from ending that would mean that, if a player pulls the lever before it's allowed, the lever would remain in a pulled position. This means that even when the chosen time of day has passed, the player cannot pull the lever again. (Until the ship has departed/landed again)

**Closed as completed by gamendegamer321** 2024-07-29 10:49 UTC

**Comment by DeCat4** [comment] 2024-07-29 23:45
i just got an idea, what if when the player pulls the lever it it just unpulls, allowing interaction again. Idk how exactly denying the lever pull functions but if re allowing interaction with it again after a pull is possible you can make it so it can work after the chosen time right?

**Comment by gamendegamer321** [comment] 2024-07-30 18:56
Yeah the problem is with unpulling. I can unpull the lever for the host (that's already how the lobby lock works) but I can't unpull it for the clients as the mod is host-only (and I don't plan on changing that).

**Comment by DeCat4** [comment] 2024-07-31 11:27
ahh, fair enough then, i thought the host has a little more control over the lever
